{
 "title": "Homework",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Database metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections in detail",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, (pg_stat_activity_count))",
       "legendFormat": "{{datname}} {{state}}"
      }
     ]
    },
    {
     "title": "Active sessions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pg_stat_activity_count{ state=\"active\"} !=0",
       "legendFormat": "{{datname}}, s: {{state}}"
      }
     ]
    },
    {
     "title": "Count general connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "pg_settings_max_connections", "legendFormat": "max_connections" },
      { "expr": "sum(pg_stat_activity_count{})", "legendFormat": "total connections" },
      {
       "expr": "sum(pg_stat_activity_count{state=\"idle\"})",
       "legendFormat": "idle sessions"
      },
      {
       "expr": "sum(pg_stat_activity_count{state=\"active\"})",
       "legendFormat": "active sessions"
      },
      {
       "expr": "sum(pg_stat_activity_count{instance=\"$instance\",state=\"idle in transaction\"})",
       "legendFormat": "idle in transaction sessions"
      },
      {
       "expr": "sum(pg_stat_activity_count{instance=\"$instance\",state=\"idle in transaction (aborted)\"})",
       "legendFormat": "idle in transaction (aborted) sessions"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod!=\"\"}[5m]))\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum by (pod) (container_memory_working_set_bytes{pod != \"\"}) / 1000 / 1000 / 1000\n",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingress metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 23, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) ",
       "legendFormat": "0.95"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])) by (le)) ",
       "legendFormat": "0.5"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])) by (le)) ",
       "legendFormat": "0.99"
      },
      {
       "expr": "histogram_quantile(1, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])) by (le)) ",
       "legendFormat": "1"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_requests[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 11, "y": 13 },
     "targets": [
      { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{handler}}" }
     ]
    }
   ]
  },
  { "title": "Application metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, handler)) ",
     "legendFormat": "{{handler}}-0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, handler)) ",
     "legendFormat": "{{handler}}-0.5"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, handler)) ",
     "legendFormat": "{{handler}}-0.99"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, handler)) ",
     "legendFormat": "{{handler}}-max"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_requests_total{status=\"5xx\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 12, "y": 16 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{handler}}" }
   ]
  }
 ]
}