helmDefaults:
  wait: true
  waitForJobs: true
  historyMax: 3
  createNamespace: true

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: cetic
    url: https://cetic.github.io/helm-charts

releases:
  - name: prometheus-operator
    chart: bitnami/kube-prometheus
    version: 8.0.1
    namespace: kube-system
    values:
      - prometheus:
          ingress:
            enabled: true
            pathType: Prefix
            hostname: prom.localhost
            path: /
            ingressClassName: nginx
  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.1.1
    namespace: kube-system
    needs:
      - kube-system/prometheus-operator
    values:
      - controller:
          metrics:
            enabled: true
            serviceMonitor:
              additionalLabels:
                release: prometheus
              enabled: true
        exporters:
          kube-state-metrics:
            enabled: true
        kubelet:
          enabled: true

  - name: grafana
    chart: bitnami/grafana
    version: 7.9.4
    namespace: kube-system
    needs:
      - kube-system/ingress-nginx
    values:
      - values/grafana.yaml.gotmpl
      - ingress:
          enabled: true
          pathType: Prefix
          hostname: grafana.localhost
          path: /
          ingressClassName: nginx
        config:
          useGrafanaIniFile: true
          grafanaIniConfigMap: grafanaconfig
        admin:
          user: admin
          password: admin
        datasources:
          secretName: grafana-datasources
        dashboardsProvider:
          enabled: true
        dashboardsConfigMaps:
          - configMapName: grafana-dashboard
            fileName: dashboard.json
  - name: postgresql
    version: 11.6.3
    chart: bitnami/postgresql
    namespace: default
    needs:
      - kube-system/prometheus-operator
    values:
      - fullnameOverride: "db"
        auth:
          postgresPassword: ololo
          database: homework
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
  - name: application
    chart: ./charts/homework-6
    namespace: default
    recreatePods: true
    needs:
      - kube-system/ingress-nginx
      - default/postgresql
    values:
      - withStress: true
        image:
          pullPolicy: Always
          repository: {{ requiredEnv "IMAGE" }}
          tag: latest
        ingress:
          enabled: true
          className: "nginx"
          hosts:
            - host: localhost
              paths:
                - path: "/"
                  pathType: Prefix
        env:
          - name: DATABASE_USER
            value: postgres
          - name: DATABASE_PASSWORD
            value: "ololo"
          - name: DATABASE_URL
            value: postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@db:5432/homework


