{{ if false }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "homework-6.fullname" . }}
  labels:
    {{- include "homework-6.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "homework-6.fullname" . }}
  namespaceSelector:
    matchNames:
    - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "homework-6.selectorLabels" . | nindent 6 }}
  endpoints:
  - interval: 15s
    port: http
    path: /metrics
{{ end }}